version: '3.8'
services:
  nest-api:
    container_name: next-blog-api
    networks: 
      - breeze_default
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8090:3000'
    env_file:
      - .env.production
